namespace AnchorSetup.Localization;

// The remaining 12 installer languages (uk, zh, et, de, fr, pt, ja, ko, pl, it, nl, tr).
// Split from SetupLoc.cs purely for readability; every dictionary carries the full key set.
public sealed partial class SetupLoc
{
    // Expression-bodied (not a field) so it's built lazily from BuildAll — by then every
    // _xx dictionary below is initialized, sidestepping static-field initialization order.
    private static Dictionary<string, Dictionary<string, string>> More => new()
    {
        ["uk"] = _uk, ["zh"] = _zh, ["et"] = _et, ["de"] = _de, ["fr"] = _fr, ["pt"] = _pt,
        ["ja"] = _ja, ["ko"] = _ko, ["pl"] = _pl, ["it"] = _it, ["nl"] = _nl, ["tr"] = _tr,
    };

    private static readonly Dictionary<string, string> _uk = new()
    {
        ["win_subtitle"] = "Встановлення",
        ["step_welcome"] = "Вітаємо", ["step_license"] = "Ліцензія", ["step_options"] = "Параметри",
        ["step_install"] = "Встановлення", ["step_finish"] = "Готово",
        ["btn_back"] = "Назад", ["btn_next"] = "Далі", ["btn_install"] = "Встановити",
        ["btn_cancel"] = "Скасувати", ["btn_finish"] = "Завершити", ["btn_browse"] = "Огляд",
        ["wel_title"] = "Вітаємо в Anchor Launcher",
        ["wel_sub"] = "Преміальний лаунчер Minecraft: Java Edition. Майстер встановить Anchor на ваш ПК за кілька секунд.",
        ["wel_lang_label"] = "Виберіть мову",
        ["wel_lang_hint"] = "Anchor Launcher запуститься цією мовою — її можна змінити в налаштуваннях будь-коли.",
        ["wel_b1"] = "Вхід одним кліком через акаунти Microsoft і Ely.by",
        ["wel_b2"] = "Вбудований каталог модів, шейдерів і збірок",
        ["wel_b3"] = "Іконки збірок, облік часу гри та 15 мов",
        ["lic_title"] = "Ліцензійна угода",
        ["lic_sub"] = "Прочитайте та прийміть умови, перш ніж продовжити.",
        ["lic_accept"] = "Я прочитав(ла) і приймаю ліцензійну угоду",
        ["opt_title"] = "Параметри встановлення",
        ["opt_sub"] = "Виберіть, куди встановити Anchor і як він інтегрується з Windows.",
        ["opt_location"] = "Папка встановлення",
        ["opt_loc_hint"] = "Anchor встановлюється лише для вас — права адміністратора не потрібні.",
        ["opt_desktop"] = "Створити ярлик на робочому столі",
        ["opt_startmenu"] = "Додати Anchor до меню «Пуск»",
        ["opt_startup"] = "Запускати Anchor під час старту Windows",
        ["opt_space"] = "Потрібно місця",
        ["ins_title"] = "Встановлення Anchor Launcher",
        ["ins_sub"] = "Зачекайте трохи — це займе лише мить.",
        ["ins_preparing"] = "Підготовка…",
        ["ins_downloading"] = "Завантаження Anchor Launcher…",
        ["ins_files"] = "Запис файлів програми…",
        ["ins_shortcuts"] = "Створення ярликів…",
        ["ins_language"] = "Застосування мови…",
        ["ins_registering"] = "Реєстрація Anchor…",
        ["ins_failed"] = "Помилка встановлення",
        ["fin_title"] = "Готово!",
        ["fin_sub"] = "Anchor Launcher встановлено та готовий до відплиття.",
        ["fin_launch"] = "Відкрити Anchor Launcher зараз",
        ["cancel_title"] = "Скасувати встановлення?",
        ["cancel_body"] = "Anchor ще не встановлено повністю. Ви впевнені, що хочете вийти?",
        ["cancel_yes"] = "Вийти", ["cancel_no"] = "Продовжити встановлення",
        ["un_title"] = "Видалення Anchor Launcher",
        ["un_body"] = "Anchor Launcher буде видалено з вашого ПК. Ваші світи, акаунти й налаштування збережуться, якщо не вказано інше.",
        ["un_remove"] = "Видалити", ["un_keepdata"] = "Також видалити мої дані (світи, акаунти, налаштування)",
        ["un_removing"] = "Видалення Anchor Launcher…", ["un_done"] = "Anchor Launcher видалено.",
    };

    private static readonly Dictionary<string, string> _zh = new()
    {
        ["win_subtitle"] = "安装",
        ["step_welcome"] = "欢迎", ["step_license"] = "许可协议", ["step_options"] = "选项",
        ["step_install"] = "安装", ["step_finish"] = "完成",
        ["btn_back"] = "上一步", ["btn_next"] = "下一步", ["btn_install"] = "安装",
        ["btn_cancel"] = "取消", ["btn_finish"] = "完成", ["btn_browse"] = "浏览",
        ["wel_title"] = "欢迎使用 Anchor Launcher",
        ["wel_sub"] = "高级 Minecraft：Java 版启动器。此向导将在几秒钟内为你的电脑安装 Anchor。",
        ["wel_lang_label"] = "选择你的语言",
        ["wel_lang_hint"] = "Anchor Launcher 将以此语言启动 — 你可以随时在设置中更改。",
        ["wel_b1"] = "一键登录 Microsoft 与 Ely.by 账户",
        ["wel_b2"] = "内置模组、光影与整合包商店",
        ["wel_b3"] = "实例图标、游戏时长统计与 15 种语言",
        ["lic_title"] = "许可协议",
        ["lic_sub"] = "继续之前，请阅读并接受条款。",
        ["lic_accept"] = "我已阅读并接受许可协议",
        ["opt_title"] = "安装选项",
        ["opt_sub"] = "选择 Anchor 的安装位置及其与 Windows 的集成方式。",
        ["opt_location"] = "安装位置",
        ["opt_loc_hint"] = "Anchor 仅为你安装 — 无需管理员权限。",
        ["opt_desktop"] = "创建桌面快捷方式",
        ["opt_startmenu"] = "添加到「开始」菜单",
        ["opt_startup"] = "Windows 启动时运行 Anchor",
        ["opt_space"] = "所需空间",
        ["ins_title"] = "正在安装 Anchor Launcher",
        ["ins_sub"] = "请稍候 — 马上就好。",
        ["ins_preparing"] = "正在准备…",
        ["ins_downloading"] = "正在下载 Anchor Launcher…",
        ["ins_files"] = "正在写入程序文件…",
        ["ins_shortcuts"] = "正在创建快捷方式…",
        ["ins_language"] = "正在应用你的语言…",
        ["ins_registering"] = "正在注册 Anchor…",
        ["ins_failed"] = "安装失败",
        ["fin_title"] = "全部完成！",
        ["fin_sub"] = "Anchor Launcher 已安装完成，随时可以起航。",
        ["fin_launch"] = "立即启动 Anchor Launcher",
        ["cancel_title"] = "取消安装？",
        ["cancel_body"] = "Anchor 尚未安装完成。确定要退出吗？",
        ["cancel_yes"] = "退出安装", ["cancel_no"] = "继续安装",
        ["un_title"] = "卸载 Anchor Launcher",
        ["un_body"] = "这将从你的电脑中移除 Anchor Launcher。除非你另行选择，否则你的世界、账户和设置都会保留。",
        ["un_remove"] = "移除", ["un_keepdata"] = "同时删除我的数据（世界、账户、设置）",
        ["un_removing"] = "正在移除 Anchor Launcher…", ["un_done"] = "Anchor Launcher 已被移除。",
    };

    private static readonly Dictionary<string, string> _et = new()
    {
        ["win_subtitle"] = "Paigaldus",
        ["step_welcome"] = "Tere tulemast", ["step_license"] = "Litsents", ["step_options"] = "Valikud",
        ["step_install"] = "Paigaldus", ["step_finish"] = "Valmis",
        ["btn_back"] = "Tagasi", ["btn_next"] = "Edasi", ["btn_install"] = "Paigalda",
        ["btn_cancel"] = "Tühista", ["btn_finish"] = "Lõpeta", ["btn_browse"] = "Sirvi",
        ["wel_title"] = "Tere tulemast Anchor Launcherisse",
        ["wel_sub"] = "Esmaklassiline Minecraft: Java Editioni käivitaja. See viisard paigaldab Anchori su arvutisse mõne sekundiga.",
        ["wel_lang_label"] = "Vali oma keel",
        ["wel_lang_hint"] = "Anchor Launcher käivitub selles keeles — saad seda seadetes igal ajal muuta.",
        ["wel_b1"] = "Ühe klõpsuga sisselogimine Microsofti ja Ely.by kontoga",
        ["wel_b2"] = "Sisseehitatud modide, varjutajate ja modpakkide pood",
        ["wel_b3"] = "Instantsi ikoonid, mänguaja arvestus ja 15 keelt",
        ["lic_title"] = "Litsentsileping",
        ["lic_sub"] = "Palun loe tingimused läbi ja nõustu nendega enne jätkamist.",
        ["lic_accept"] = "Olen litsentsilepingu läbi lugenud ja nõustun sellega",
        ["opt_title"] = "Paigalduse valikud",
        ["opt_sub"] = "Vali, kuhu Anchor paigaldatakse ja kuidas see Windowsiga sobitub.",
        ["opt_location"] = "Paigalduse asukoht",
        ["opt_loc_hint"] = "Anchor paigaldatakse ainult sinule — administraatori õigusi pole vaja.",
        ["opt_desktop"] = "Loo töölaua otsetee",
        ["opt_startmenu"] = "Lisa Anchor Start-menüüsse",
        ["opt_startup"] = "Käivita Anchor Windowsi käivitumisel",
        ["opt_space"] = "Vajalik ruum",
        ["ins_title"] = "Anchor Launcheri paigaldamine",
        ["ins_sub"] = "Üks hetk — see võtab vaid silmapilgu.",
        ["ins_preparing"] = "Ettevalmistamine…",
        ["ins_downloading"] = "Anchor Launcheri allalaadimine…",
        ["ins_files"] = "Programmifailide kirjutamine…",
        ["ins_shortcuts"] = "Otseteede loomine…",
        ["ins_language"] = "Keele rakendamine…",
        ["ins_registering"] = "Anchori registreerimine…",
        ["ins_failed"] = "Paigaldamine ebaõnnestus",
        ["fin_title"] = "Kõik valmis!",
        ["fin_sub"] = "Anchor Launcher on paigaldatud ja valmis purjetama.",
        ["fin_launch"] = "Ava Anchor Launcher kohe",
        ["cancel_title"] = "Kas katkestada paigaldus?",
        ["cancel_body"] = "Anchori paigaldamine pole veel lõppenud. Kas oled kindel, et soovid väljuda?",
        ["cancel_yes"] = "Välju", ["cancel_no"] = "Jätka paigaldamist",
        ["un_title"] = "Anchor Launcheri eemaldamine",
        ["un_body"] = "See eemaldab Anchor Launcheri su arvutist. Sinu maailmad, kontod ja seaded säilivad, kui sa ei vali teisiti.",
        ["un_remove"] = "Eemalda", ["un_keepdata"] = "Kustuta ka minu andmed (maailmad, kontod, seaded)",
        ["un_removing"] = "Anchor Launcheri eemaldamine…", ["un_done"] = "Anchor Launcher on eemaldatud.",
    };

    private static readonly Dictionary<string, string> _de = new()
    {
        ["win_subtitle"] = "Setup",
        ["step_welcome"] = "Willkommen", ["step_license"] = "Lizenz", ["step_options"] = "Optionen",
        ["step_install"] = "Installation", ["step_finish"] = "Fertig",
        ["btn_back"] = "Zurück", ["btn_next"] = "Weiter", ["btn_install"] = "Installieren",
        ["btn_cancel"] = "Abbrechen", ["btn_finish"] = "Fertigstellen", ["btn_browse"] = "Durchsuchen",
        ["wel_title"] = "Willkommen bei Anchor Launcher",
        ["wel_sub"] = "Der Premium-Launcher für Minecraft: Java Edition. Dieser Assistent richtet Anchor in wenigen Sekunden auf deinem PC ein.",
        ["wel_lang_label"] = "Sprache auswählen",
        ["wel_lang_hint"] = "Anchor Launcher startet in dieser Sprache – du kannst sie jederzeit in den Einstellungen ändern.",
        ["wel_b1"] = "Anmeldung mit einem Klick über Microsoft- und Ely.by-Konten",
        ["wel_b2"] = "Integrierter Marktplatz für Mods, Shader und Modpacks",
        ["wel_b3"] = "Instanz-Icons, Spielzeiterfassung und 15 Sprachen",
        ["lic_title"] = "Lizenzvereinbarung",
        ["lic_sub"] = "Bitte lies und akzeptiere die Bedingungen, bevor du fortfährst.",
        ["lic_accept"] = "Ich habe die Lizenzvereinbarung gelesen und akzeptiere sie",
        ["opt_title"] = "Installationsoptionen",
        ["opt_sub"] = "Lege fest, wohin Anchor installiert wird und wie es sich in Windows einfügt.",
        ["opt_location"] = "Installationsort",
        ["opt_loc_hint"] = "Anchor wird nur für dich installiert – keine Administratorrechte nötig.",
        ["opt_desktop"] = "Desktop-Verknüpfung erstellen",
        ["opt_startmenu"] = "Anchor zum Startmenü hinzufügen",
        ["opt_startup"] = "Anchor beim Start von Windows ausführen",
        ["opt_space"] = "Benötigter Speicher",
        ["ins_title"] = "Anchor Launcher wird installiert",
        ["ins_sub"] = "Einen Moment – das dauert nur einen Augenblick.",
        ["ins_preparing"] = "Wird vorbereitet…",
        ["ins_downloading"] = "Anchor Launcher wird heruntergeladen…",
        ["ins_files"] = "Programmdateien werden geschrieben…",
        ["ins_shortcuts"] = "Verknüpfungen werden erstellt…",
        ["ins_language"] = "Sprache wird übernommen…",
        ["ins_registering"] = "Anchor wird registriert…",
        ["ins_failed"] = "Installation fehlgeschlagen",
        ["fin_title"] = "Fertig!",
        ["fin_sub"] = "Anchor Launcher ist installiert und bereit zum Ablegen.",
        ["fin_launch"] = "Anchor Launcher jetzt starten",
        ["cancel_title"] = "Installation abbrechen?",
        ["cancel_body"] = "Anchor ist noch nicht fertig installiert. Möchtest du wirklich beenden?",
        ["cancel_yes"] = "Beenden", ["cancel_no"] = "Weiter installieren",
        ["un_title"] = "Anchor Launcher deinstallieren",
        ["un_body"] = "Dadurch wird Anchor Launcher von deinem PC entfernt. Deine Welten, Konten und Einstellungen bleiben erhalten, sofern du nichts anderes wählst.",
        ["un_remove"] = "Entfernen", ["un_keepdata"] = "Auch meine Daten löschen (Welten, Konten, Einstellungen)",
        ["un_removing"] = "Anchor Launcher wird entfernt…", ["un_done"] = "Anchor Launcher wurde entfernt.",
    };

    private static readonly Dictionary<string, string> _fr = new()
    {
        ["win_subtitle"] = "Installation",
        ["step_welcome"] = "Bienvenue", ["step_license"] = "Licence", ["step_options"] = "Options",
        ["step_install"] = "Installation", ["step_finish"] = "Terminé",
        ["btn_back"] = "Retour", ["btn_next"] = "Suivant", ["btn_install"] = "Installer",
        ["btn_cancel"] = "Annuler", ["btn_finish"] = "Terminer", ["btn_browse"] = "Parcourir",
        ["wel_title"] = "Bienvenue dans Anchor Launcher",
        ["wel_sub"] = "Le launcher premium de Minecraft : Java Edition. Cet assistant installe Anchor sur votre PC en quelques secondes.",
        ["wel_lang_label"] = "Choisissez votre langue",
        ["wel_lang_hint"] = "Anchor Launcher démarrera dans cette langue — vous pouvez la changer à tout moment dans les Paramètres.",
        ["wel_b1"] = "Connexion en un clic avec les comptes Microsoft et Ely.by",
        ["wel_b2"] = "Boutique intégrée de mods, shaders et modpacks",
        ["wel_b3"] = "Icônes par instance, suivi du temps de jeu et 15 langues",
        ["lic_title"] = "Contrat de licence",
        ["lic_sub"] = "Veuillez lire et accepter les conditions avant de continuer.",
        ["lic_accept"] = "J'ai lu et j'accepte le contrat de licence",
        ["opt_title"] = "Options d'installation",
        ["opt_sub"] = "Choisissez où Anchor s'installe et comment il s'intègre à Windows.",
        ["opt_location"] = "Dossier d'installation",
        ["opt_loc_hint"] = "Anchor s'installe uniquement pour vous — aucun droit administrateur requis.",
        ["opt_desktop"] = "Créer un raccourci sur le Bureau",
        ["opt_startmenu"] = "Ajouter Anchor au menu Démarrer",
        ["opt_startup"] = "Lancer Anchor au démarrage de Windows",
        ["opt_space"] = "Espace requis",
        ["ins_title"] = "Installation d'Anchor Launcher",
        ["ins_sub"] = "Patientez — ce ne sera qu'un instant.",
        ["ins_preparing"] = "Préparation…",
        ["ins_downloading"] = "Téléchargement d'Anchor Launcher…",
        ["ins_files"] = "Écriture des fichiers du programme…",
        ["ins_shortcuts"] = "Création des raccourcis…",
        ["ins_language"] = "Application de votre langue…",
        ["ins_registering"] = "Enregistrement d'Anchor…",
        ["ins_failed"] = "Échec de l'installation",
        ["fin_title"] = "Tout est prêt !",
        ["fin_sub"] = "Anchor Launcher est installé et prêt à larguer les amarres.",
        ["fin_launch"] = "Lancer Anchor Launcher maintenant",
        ["cancel_title"] = "Annuler l'installation ?",
        ["cancel_body"] = "Anchor n'est pas encore complètement installé. Voulez-vous vraiment quitter ?",
        ["cancel_yes"] = "Quitter", ["cancel_no"] = "Continuer l'installation",
        ["un_title"] = "Désinstaller Anchor Launcher",
        ["un_body"] = "Cela supprime Anchor Launcher de votre PC. Vos mondes, comptes et paramètres sont conservés, sauf choix contraire.",
        ["un_remove"] = "Supprimer", ["un_keepdata"] = "Supprimer aussi mes données (mondes, comptes, paramètres)",
        ["un_removing"] = "Suppression d'Anchor Launcher…", ["un_done"] = "Anchor Launcher a été supprimé.",
    };

    private static readonly Dictionary<string, string> _pt = new()
    {
        ["win_subtitle"] = "Instalação",
        ["step_welcome"] = "Bem-vindo", ["step_license"] = "Licença", ["step_options"] = "Opções",
        ["step_install"] = "Instalar", ["step_finish"] = "Concluído",
        ["btn_back"] = "Voltar", ["btn_next"] = "Avançar", ["btn_install"] = "Instalar",
        ["btn_cancel"] = "Cancelar", ["btn_finish"] = "Concluir", ["btn_browse"] = "Procurar",
        ["wel_title"] = "Bem-vindo ao Anchor Launcher",
        ["wel_sub"] = "O launcher premium de Minecraft: Java Edition. Este assistente instala o Anchor no seu PC em poucos segundos.",
        ["wel_lang_label"] = "Escolha o seu idioma",
        ["wel_lang_hint"] = "O Anchor Launcher iniciará neste idioma — você pode alterá-lo a qualquer momento nas Configurações.",
        ["wel_b1"] = "Login com um clique usando contas Microsoft e Ely.by",
        ["wel_b2"] = "Loja integrada de mods, shaders e modpacks",
        ["wel_b3"] = "Ícones por instância, registro de tempo de jogo e 15 idiomas",
        ["lic_title"] = "Contrato de Licença",
        ["lic_sub"] = "Leia e aceite os termos antes de continuar.",
        ["lic_accept"] = "Li e aceito o contrato de licença",
        ["opt_title"] = "Opções de instalação",
        ["opt_sub"] = "Escolha onde o Anchor fica e como ele se integra ao Windows.",
        ["opt_location"] = "Local de instalação",
        ["opt_loc_hint"] = "O Anchor é instalado apenas para você — sem necessidade de permissões de administrador.",
        ["opt_desktop"] = "Criar um atalho na Área de Trabalho",
        ["opt_startmenu"] = "Adicionar o Anchor ao menu Iniciar",
        ["opt_startup"] = "Abrir o Anchor ao iniciar o Windows",
        ["opt_space"] = "Espaço necessário",
        ["ins_title"] = "Instalando o Anchor Launcher",
        ["ins_sub"] = "Aguarde um momento — será rápido.",
        ["ins_preparing"] = "Preparando…",
        ["ins_downloading"] = "Baixando o Anchor Launcher…",
        ["ins_files"] = "Gravando os arquivos do programa…",
        ["ins_shortcuts"] = "Criando atalhos…",
        ["ins_language"] = "Aplicando o seu idioma…",
        ["ins_registering"] = "Registrando o Anchor…",
        ["ins_failed"] = "Falha na instalação",
        ["fin_title"] = "Tudo pronto!",
        ["fin_sub"] = "O Anchor Launcher está instalado e pronto para zarpar.",
        ["fin_launch"] = "Abrir o Anchor Launcher agora",
        ["cancel_title"] = "Cancelar a instalação?",
        ["cancel_body"] = "O Anchor ainda não terminou de instalar. Tem certeza de que deseja sair?",
        ["cancel_yes"] = "Sair", ["cancel_no"] = "Continuar instalando",
        ["un_title"] = "Desinstalar o Anchor Launcher",
        ["un_body"] = "Isso remove o Anchor Launcher do seu PC. Seus mundos, contas e configurações são mantidos, a menos que você escolha o contrário.",
        ["un_remove"] = "Remover", ["un_keepdata"] = "Também excluir meus dados (mundos, contas, configurações)",
        ["un_removing"] = "Removendo o Anchor Launcher…", ["un_done"] = "O Anchor Launcher foi removido.",
    };

    private static readonly Dictionary<string, string> _ja = new()
    {
        ["win_subtitle"] = "セットアップ",
        ["step_welcome"] = "ようこそ", ["step_license"] = "ライセンス", ["step_options"] = "オプション",
        ["step_install"] = "インストール", ["step_finish"] = "完了",
        ["btn_back"] = "戻る", ["btn_next"] = "次へ", ["btn_install"] = "インストール",
        ["btn_cancel"] = "キャンセル", ["btn_finish"] = "完了", ["btn_browse"] = "参照",
        ["wel_title"] = "Anchor Launcher へようこそ",
        ["wel_sub"] = "プレミアムな Minecraft: Java Edition ランチャーです。このウィザードが数秒で Anchor をセットアップします。",
        ["wel_lang_label"] = "言語を選択",
        ["wel_lang_hint"] = "Anchor Launcher はこの言語で起動します。設定からいつでも変更できます。",
        ["wel_b1"] = "Microsoft と Ely.by アカウントでワンクリックサインイン",
        ["wel_b2"] = "Mod・シェーダー・Modpack の内蔵マーケットプレイス",
        ["wel_b3"] = "インスタンスごとのアイコン、プレイ時間記録、15 言語対応",
        ["lic_title"] = "ライセンス契約",
        ["lic_sub"] = "続行する前に、条項をお読みのうえ同意してください。",
        ["lic_accept"] = "ライセンス契約を読み、同意します",
        ["opt_title"] = "インストールオプション",
        ["opt_sub"] = "Anchor のインストール先と Windows への組み込み方法を選びます。",
        ["opt_location"] = "インストール先",
        ["opt_loc_hint"] = "Anchor はあなた専用にインストールされます。管理者権限は不要です。",
        ["opt_desktop"] = "デスクトップにショートカットを作成",
        ["opt_startmenu"] = "Anchor をスタートメニューに追加",
        ["opt_startup"] = "Windows 起動時に Anchor を起動",
        ["opt_space"] = "必要な容量",
        ["ins_title"] = "Anchor Launcher をインストール中",
        ["ins_sub"] = "少々お待ちください。すぐに終わります。",
        ["ins_preparing"] = "準備中…",
        ["ins_downloading"] = "Anchor Launcher をダウンロード中…",
        ["ins_files"] = "プログラムファイルを書き込み中…",
        ["ins_shortcuts"] = "ショートカットを作成中…",
        ["ins_language"] = "言語を適用中…",
        ["ins_registering"] = "Anchor を登録中…",
        ["ins_failed"] = "インストールに失敗しました",
        ["fin_title"] = "完了しました！",
        ["fin_sub"] = "Anchor Launcher のインストールが完了し、出航の準備が整いました。",
        ["fin_launch"] = "今すぐ Anchor Launcher を起動",
        ["cancel_title"] = "インストールを中止しますか？",
        ["cancel_body"] = "Anchor のインストールはまだ完了していません。本当に終了しますか？",
        ["cancel_yes"] = "終了する", ["cancel_no"] = "インストールを続行",
        ["un_title"] = "Anchor Launcher をアンインストール",
        ["un_body"] = "Anchor Launcher を PC から削除します。別途選択しない限り、ワールド・アカウント・設定は保持されます。",
        ["un_remove"] = "削除", ["un_keepdata"] = "データ（ワールド・アカウント・設定）も削除する",
        ["un_removing"] = "Anchor Launcher を削除中…", ["un_done"] = "Anchor Launcher が削除されました。",
    };

    private static readonly Dictionary<string, string> _ko = new()
    {
        ["win_subtitle"] = "설치",
        ["step_welcome"] = "환영", ["step_license"] = "라이선스", ["step_options"] = "옵션",
        ["step_install"] = "설치", ["step_finish"] = "완료",
        ["btn_back"] = "뒤로", ["btn_next"] = "다음", ["btn_install"] = "설치",
        ["btn_cancel"] = "취소", ["btn_finish"] = "마침", ["btn_browse"] = "찾아보기",
        ["wel_title"] = "Anchor Launcher에 오신 것을 환영합니다",
        ["wel_sub"] = "프리미엄 Minecraft: Java Edition 런처입니다. 이 마법사가 몇 초 만에 Anchor를 PC에 설치합니다.",
        ["wel_lang_label"] = "언어 선택",
        ["wel_lang_hint"] = "Anchor Launcher가 이 언어로 시작됩니다 — 설정에서 언제든지 변경할 수 있습니다.",
        ["wel_b1"] = "Microsoft 및 Ely.by 계정으로 원클릭 로그인",
        ["wel_b2"] = "모드·셰이더·모드팩 내장 마켓플레이스",
        ["wel_b3"] = "인스턴스별 아이콘, 플레이 시간 기록, 15개 언어 지원",
        ["lic_title"] = "라이선스 계약",
        ["lic_sub"] = "계속하기 전에 약관을 읽고 동의해 주세요.",
        ["lic_accept"] = "라이선스 계약을 읽었으며 이에 동의합니다",
        ["opt_title"] = "설치 옵션",
        ["opt_sub"] = "Anchor를 설치할 위치와 Windows에 통합되는 방식을 선택하세요.",
        ["opt_location"] = "설치 위치",
        ["opt_loc_hint"] = "Anchor는 사용자 전용으로 설치되며 관리자 권한이 필요하지 않습니다.",
        ["opt_desktop"] = "바탕 화면 바로 가기 만들기",
        ["opt_startmenu"] = "시작 메뉴에 Anchor 추가",
        ["opt_startup"] = "Windows 시작 시 Anchor 실행",
        ["opt_space"] = "필요한 공간",
        ["ins_title"] = "Anchor Launcher 설치 중",
        ["ins_sub"] = "잠시만 기다려 주세요 — 곧 완료됩니다.",
        ["ins_preparing"] = "준비 중…",
        ["ins_downloading"] = "Anchor Launcher 다운로드 중…",
        ["ins_files"] = "프로그램 파일 기록 중…",
        ["ins_shortcuts"] = "바로 가기 만드는 중…",
        ["ins_language"] = "언어 적용 중…",
        ["ins_registering"] = "Anchor 등록 중…",
        ["ins_failed"] = "설치 실패",
        ["fin_title"] = "모두 완료!",
        ["fin_sub"] = "Anchor Launcher가 설치되어 출항할 준비가 되었습니다.",
        ["fin_launch"] = "지금 Anchor Launcher 실행",
        ["cancel_title"] = "설치를 취소할까요?",
        ["cancel_body"] = "Anchor 설치가 아직 끝나지 않았습니다. 정말 종료하시겠어요?",
        ["cancel_yes"] = "종료", ["cancel_no"] = "계속 설치",
        ["un_title"] = "Anchor Launcher 제거",
        ["un_body"] = "Anchor Launcher를 PC에서 제거합니다. 다르게 선택하지 않는 한 월드, 계정, 설정은 유지됩니다.",
        ["un_remove"] = "제거", ["un_keepdata"] = "내 데이터(월드, 계정, 설정)도 삭제",
        ["un_removing"] = "Anchor Launcher 제거 중…", ["un_done"] = "Anchor Launcher가 제거되었습니다.",
    };

    private static readonly Dictionary<string, string> _pl = new()
    {
        ["win_subtitle"] = "Instalacja",
        ["step_welcome"] = "Powitanie", ["step_license"] = "Licencja", ["step_options"] = "Opcje",
        ["step_install"] = "Instalacja", ["step_finish"] = "Gotowe",
        ["btn_back"] = "Wstecz", ["btn_next"] = "Dalej", ["btn_install"] = "Zainstaluj",
        ["btn_cancel"] = "Anuluj", ["btn_finish"] = "Zakończ", ["btn_browse"] = "Przeglądaj",
        ["wel_title"] = "Witaj w Anchor Launcher",
        ["wel_sub"] = "Premium launcher do Minecraft: Java Edition. Ten kreator skonfiguruje Anchor na Twoim komputerze w kilka sekund.",
        ["wel_lang_label"] = "Wybierz język",
        ["wel_lang_hint"] = "Anchor Launcher uruchomi się w tym języku — możesz go zmienić w każdej chwili w Ustawieniach.",
        ["wel_b1"] = "Logowanie jednym kliknięciem przez konta Microsoft i Ely.by",
        ["wel_b2"] = "Wbudowany sklep z modami, shaderami i modpackami",
        ["wel_b3"] = "Ikony instancji, śledzenie czasu gry i 15 języków",
        ["lic_title"] = "Umowa licencyjna",
        ["lic_sub"] = "Przeczytaj i zaakceptuj warunki przed kontynuowaniem.",
        ["lic_accept"] = "Przeczytałem(am) i akceptuję umowę licencyjną",
        ["opt_title"] = "Opcje instalacji",
        ["opt_sub"] = "Wybierz, gdzie zainstalować Anchor i jak ma się zintegrować z Windows.",
        ["opt_location"] = "Lokalizacja instalacji",
        ["opt_loc_hint"] = "Anchor jest instalowany tylko dla Ciebie — bez uprawnień administratora.",
        ["opt_desktop"] = "Utwórz skrót na pulpicie",
        ["opt_startmenu"] = "Dodaj Anchor do menu Start",
        ["opt_startup"] = "Uruchamiaj Anchor przy starcie Windows",
        ["opt_space"] = "Wymagane miejsce",
        ["ins_title"] = "Instalowanie Anchor Launcher",
        ["ins_sub"] = "Chwila cierpliwości — to potrwa tylko moment.",
        ["ins_preparing"] = "Przygotowywanie…",
        ["ins_downloading"] = "Pobieranie Anchor Launcher…",
        ["ins_files"] = "Zapisywanie plików programu…",
        ["ins_shortcuts"] = "Tworzenie skrótów…",
        ["ins_language"] = "Stosowanie języka…",
        ["ins_registering"] = "Rejestrowanie Anchor…",
        ["ins_failed"] = "Instalacja nie powiodła się",
        ["fin_title"] = "Gotowe!",
        ["fin_sub"] = "Anchor Launcher jest zainstalowany i gotowy do wypłynięcia.",
        ["fin_launch"] = "Uruchom Anchor Launcher teraz",
        ["cancel_title"] = "Anulować instalację?",
        ["cancel_body"] = "Anchor nie został jeszcze w pełni zainstalowany. Na pewno chcesz wyjść?",
        ["cancel_yes"] = "Zakończ", ["cancel_no"] = "Kontynuuj instalację",
        ["un_title"] = "Odinstaluj Anchor Launcher",
        ["un_body"] = "Spowoduje to usunięcie Anchor Launcher z komputera. Twoje światy, konta i ustawienia zostaną zachowane, chyba że wybierzesz inaczej.",
        ["un_remove"] = "Usuń", ["un_keepdata"] = "Usuń też moje dane (światy, konta, ustawienia)",
        ["un_removing"] = "Usuwanie Anchor Launcher…", ["un_done"] = "Anchor Launcher został usunięty.",
    };

    private static readonly Dictionary<string, string> _it = new()
    {
        ["win_subtitle"] = "Installazione",
        ["step_welcome"] = "Benvenuto", ["step_license"] = "Licenza", ["step_options"] = "Opzioni",
        ["step_install"] = "Installa", ["step_finish"] = "Fine",
        ["btn_back"] = "Indietro", ["btn_next"] = "Avanti", ["btn_install"] = "Installa",
        ["btn_cancel"] = "Annulla", ["btn_finish"] = "Fine", ["btn_browse"] = "Sfoglia",
        ["wel_title"] = "Benvenuto in Anchor Launcher",
        ["wel_sub"] = "Il launcher premium per Minecraft: Java Edition. Questa procedura installerà Anchor sul tuo PC in pochi secondi.",
        ["wel_lang_label"] = "Scegli la tua lingua",
        ["wel_lang_hint"] = "Anchor Launcher si avvierà in questa lingua — puoi cambiarla quando vuoi nelle Impostazioni.",
        ["wel_b1"] = "Accesso con un clic tramite account Microsoft ed Ely.by",
        ["wel_b2"] = "Store integrato di mod, shader e modpack",
        ["wel_b3"] = "Icone per istanza, registro del tempo di gioco e 15 lingue",
        ["lic_title"] = "Contratto di licenza",
        ["lic_sub"] = "Leggi e accetta i termini prima di continuare.",
        ["lic_accept"] = "Ho letto e accetto il contratto di licenza",
        ["opt_title"] = "Opzioni di installazione",
        ["opt_sub"] = "Scegli dove installare Anchor e come integrarlo in Windows.",
        ["opt_location"] = "Percorso di installazione",
        ["opt_loc_hint"] = "Anchor viene installato solo per te — nessun diritto di amministratore richiesto.",
        ["opt_desktop"] = "Crea un collegamento sul Desktop",
        ["opt_startmenu"] = "Aggiungi Anchor al menu Start",
        ["opt_startup"] = "Avvia Anchor all'avvio di Windows",
        ["opt_space"] = "Spazio richiesto",
        ["ins_title"] = "Installazione di Anchor Launcher",
        ["ins_sub"] = "Un attimo — ci vorrà solo un momento.",
        ["ins_preparing"] = "Preparazione…",
        ["ins_downloading"] = "Download di Anchor Launcher…",
        ["ins_files"] = "Scrittura dei file del programma…",
        ["ins_shortcuts"] = "Creazione dei collegamenti…",
        ["ins_language"] = "Applicazione della lingua…",
        ["ins_registering"] = "Registrazione di Anchor…",
        ["ins_failed"] = "Installazione non riuscita",
        ["fin_title"] = "Tutto pronto!",
        ["fin_sub"] = "Anchor Launcher è installato e pronto a salpare.",
        ["fin_launch"] = "Avvia Anchor Launcher ora",
        ["cancel_title"] = "Annullare l'installazione?",
        ["cancel_body"] = "Anchor non ha ancora finito di installarsi. Vuoi davvero uscire?",
        ["cancel_yes"] = "Esci", ["cancel_no"] = "Continua l'installazione",
        ["un_title"] = "Disinstalla Anchor Launcher",
        ["un_body"] = "Questo rimuove Anchor Launcher dal tuo PC. I tuoi mondi, account e impostazioni vengono mantenuti salvo diversa scelta.",
        ["un_remove"] = "Rimuovi", ["un_keepdata"] = "Elimina anche i miei dati (mondi, account, impostazioni)",
        ["un_removing"] = "Rimozione di Anchor Launcher…", ["un_done"] = "Anchor Launcher è stato rimosso.",
    };

    private static readonly Dictionary<string, string> _nl = new()
    {
        ["win_subtitle"] = "Installatie",
        ["step_welcome"] = "Welkom", ["step_license"] = "Licentie", ["step_options"] = "Opties",
        ["step_install"] = "Installeren", ["step_finish"] = "Klaar",
        ["btn_back"] = "Terug", ["btn_next"] = "Volgende", ["btn_install"] = "Installeren",
        ["btn_cancel"] = "Annuleren", ["btn_finish"] = "Voltooien", ["btn_browse"] = "Bladeren",
        ["wel_title"] = "Welkom bij Anchor Launcher",
        ["wel_sub"] = "De premium launcher voor Minecraft: Java Edition. Deze wizard installeert Anchor in enkele seconden op je pc.",
        ["wel_lang_label"] = "Kies je taal",
        ["wel_lang_hint"] = "Anchor Launcher start in deze taal — je kunt deze altijd wijzigen in de Instellingen.",
        ["wel_b1"] = "Aanmelden met één klik via Microsoft- en Ely.by-accounts",
        ["wel_b2"] = "Ingebouwde marktplaats voor mods, shaders en modpacks",
        ["wel_b3"] = "Pictogrammen per instantie, speeltijdregistratie en 15 talen",
        ["lic_title"] = "Licentieovereenkomst",
        ["lic_sub"] = "Lees en accepteer de voorwaarden voordat je doorgaat.",
        ["lic_accept"] = "Ik heb de licentieovereenkomst gelezen en ga akkoord",
        ["opt_title"] = "Installatieopties",
        ["opt_sub"] = "Kies waar Anchor komt te staan en hoe het in Windows past.",
        ["opt_location"] = "Installatielocatie",
        ["opt_loc_hint"] = "Anchor wordt alleen voor jou geïnstalleerd — geen beheerdersrechten nodig.",
        ["opt_desktop"] = "Snelkoppeling op het bureaublad maken",
        ["opt_startmenu"] = "Anchor aan het startmenu toevoegen",
        ["opt_startup"] = "Anchor starten wanneer Windows opstart",
        ["opt_space"] = "Vereiste ruimte",
        ["ins_title"] = "Anchor Launcher installeren",
        ["ins_sub"] = "Even geduld — dit duurt maar een momentje.",
        ["ins_preparing"] = "Voorbereiden…",
        ["ins_downloading"] = "Anchor Launcher downloaden…",
        ["ins_files"] = "Programmabestanden schrijven…",
        ["ins_shortcuts"] = "Snelkoppelingen maken…",
        ["ins_language"] = "Je taal toepassen…",
        ["ins_registering"] = "Anchor registreren…",
        ["ins_failed"] = "Installatie mislukt",
        ["fin_title"] = "Helemaal klaar!",
        ["fin_sub"] = "Anchor Launcher is geïnstalleerd en klaar om uit te varen.",
        ["fin_launch"] = "Anchor Launcher nu starten",
        ["cancel_title"] = "Installatie annuleren?",
        ["cancel_body"] = "Anchor is nog niet volledig geïnstalleerd. Weet je zeker dat je wilt stoppen?",
        ["cancel_yes"] = "Afsluiten", ["cancel_no"] = "Doorgaan met installeren",
        ["un_title"] = "Anchor Launcher verwijderen",
        ["un_body"] = "Hiermee wordt Anchor Launcher van je pc verwijderd. Je werelden, accounts en instellingen blijven behouden, tenzij je anders kiest.",
        ["un_remove"] = "Verwijderen", ["un_keepdata"] = "Ook mijn gegevens verwijderen (werelden, accounts, instellingen)",
        ["un_removing"] = "Anchor Launcher verwijderen…", ["un_done"] = "Anchor Launcher is verwijderd.",
    };

    private static readonly Dictionary<string, string> _tr = new()
    {
        ["win_subtitle"] = "Kurulum",
        ["step_welcome"] = "Hoş geldiniz", ["step_license"] = "Lisans", ["step_options"] = "Seçenekler",
        ["step_install"] = "Kur", ["step_finish"] = "Bitti",
        ["btn_back"] = "Geri", ["btn_next"] = "İleri", ["btn_install"] = "Kur",
        ["btn_cancel"] = "İptal", ["btn_finish"] = "Bitir", ["btn_browse"] = "Gözat",
        ["wel_title"] = "Anchor Launcher'a hoş geldiniz",
        ["wel_sub"] = "Premium Minecraft: Java Edition başlatıcısı. Bu sihirbaz Anchor'ı birkaç saniyede bilgisayarınıza kurar.",
        ["wel_lang_label"] = "Dilinizi seçin",
        ["wel_lang_hint"] = "Anchor Launcher bu dilde başlar — istediğiniz zaman Ayarlar'dan değiştirebilirsiniz.",
        ["wel_b1"] = "Microsoft ve Ely.by hesaplarıyla tek tıkla giriş",
        ["wel_b2"] = "Mod, shader ve modpack için yerleşik mağaza",
        ["wel_b3"] = "Örnek başına simgeler, oyun süresi takibi ve 15 dil",
        ["lic_title"] = "Lisans Sözleşmesi",
        ["lic_sub"] = "Devam etmeden önce lütfen şartları okuyup kabul edin.",
        ["lic_accept"] = "Lisans Sözleşmesi'ni okudum ve kabul ediyorum",
        ["opt_title"] = "Kurulum Seçenekleri",
        ["opt_sub"] = "Anchor'ın nereye kurulacağını ve Windows'a nasıl entegre olacağını seçin.",
        ["opt_location"] = "Kurulum konumu",
        ["opt_loc_hint"] = "Anchor yalnızca sizin için kurulur — yönetici izni gerekmez.",
        ["opt_desktop"] = "Masaüstü kısayolu oluştur",
        ["opt_startmenu"] = "Anchor'ı Başlat menüsüne ekle",
        ["opt_startup"] = "Windows başladığında Anchor'ı çalıştır",
        ["opt_space"] = "Gereken alan",
        ["ins_title"] = "Anchor Launcher kuruluyor",
        ["ins_sub"] = "Lütfen bekleyin — yalnızca bir an sürer.",
        ["ins_preparing"] = "Hazırlanıyor…",
        ["ins_downloading"] = "Anchor Launcher indiriliyor…",
        ["ins_files"] = "Program dosyaları yazılıyor…",
        ["ins_shortcuts"] = "Kısayollar oluşturuluyor…",
        ["ins_language"] = "Diliniz uygulanıyor…",
        ["ins_registering"] = "Anchor kaydediliyor…",
        ["ins_failed"] = "Kurulum başarısız oldu",
        ["fin_title"] = "Her şey hazır!",
        ["fin_sub"] = "Anchor Launcher kuruldu ve denize açılmaya hazır.",
        ["fin_launch"] = "Anchor Launcher'ı şimdi başlat",
        ["cancel_title"] = "Kurulum iptal edilsin mi?",
        ["cancel_body"] = "Anchor'ın kurulumu henüz bitmedi. Çıkmak istediğinizden emin misiniz?",
        ["cancel_yes"] = "Çık", ["cancel_no"] = "Kuruluma devam et",
        ["un_title"] = "Anchor Launcher'ı kaldır",
        ["un_body"] = "Bu işlem Anchor Launcher'ı bilgisayarınızdan kaldırır. Aksini seçmediğiniz sürece dünyalarınız, hesaplarınız ve ayarlarınız korunur.",
        ["un_remove"] = "Kaldır", ["un_keepdata"] = "Verilerimi de sil (dünyalar, hesaplar, ayarlar)",
        ["un_removing"] = "Anchor Launcher kaldırılıyor…", ["un_done"] = "Anchor Launcher kaldırıldı.",
    };
}
